CREATE TABLE IF NOT EXISTS otp (
  user_id INT PRIMARY KEY,
  otp_code VARCHAR(6) NOT NULL,
  expires_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '10 minutes',
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
